export default [
{ "_id" : "jwaterfaucett/awesome-foss-apps", "countall" : 46, "desc" : "A curated list of awesome production grade free and open source software organized by category" },
{ "_id" : "golang-china/gopl-zh", "countall" : 85, "desc" : "Go语言圣经中文版(已转到bitbucket.org)" },
{ "_id" : "tmallfe/tmallfe.github.io", "countall" : 174, "desc" : "天猫前端" },
{ "_id" : "phphub/phphub-ui", "countall" : 73, "desc" : "Product planing and UI Design for PHPHub App and Web site. " },
{ "_id" : "Johnhacker/MIUIJS", "countall" : 88, "desc" : "自己正在造的轮子,想改个名字，结果删除了，导致众多git记录都没了！fuck" },
{ "_id" : "futurice/ios-good-practices", "countall" : 53, "desc" : "Good ideas for iOS development, by Futurice developers." },
{ "_id" : "Rich-Harris/ramjet", "countall" : 140, "desc" : "Morph DOM elements from one state to another with smooth animations and transitions" },
{ "_id" : "Youpinadi/cssfizzbuzz", "countall" : 132, "desc" : "CSS implementation of the infamous FizzBuzz" },
{ "_id" : "MaximAbramchuck/awesome-interviews", "countall" : 2174, "desc" : ":octocat: A curated awesome list of lists of interview questions. Feel free to contribute! :mortar_board: " },
{ "_id" : "demirb/make-my-idea", "countall" : 24, "desc" : "Create, support & contribute so that ideas can become a reality." },
{ "_id" : "utkusen/hidden-tear", "countall" : 26, "desc" : "an open source ransomware-like file crypter kit" },
{ "_id" : "qiniu/qnlang", "countall" : 34, "desc" : "The Q Language (Q语言)" },
{ "_id" : "capira12/snapdrop", "countall" : 98, "desc" : "A HTML5 clone of Apple's AirDrop" },
{ "_id" : "upekkha/AppleHardwareTest", "countall" : 55, "desc" : "Apple Hardware Test Download Links" },
{ "_id" : "isocpp/CppCoreGuidelines", "countall" : 97, "desc" : "The C++ Core Guidelines are a set of tried-and-true guidelines, rules, and best practices about coding in C++" },
{ "_id" : "amontalenti/elements-of-python-style", "countall" : 533, "desc" : "Goes beyond PEP8 to discuss what makes Python code feel great. A Strunk & White for Python." },
{ "_id" : "ujjwalkarn/Machine-Learning-Tutorials", "countall" : 306, "desc" : "machine learning and deep learning tutorials, articles and other resources " },
{ "_id" : "syaning/awesome-frontend", "countall" : 75, "desc" : "Awesome frontend." },
{ "_id" : "petehunt/react-roadmap", "countall" : 652, "desc" : "Your guide to the (sometimes overwhelming!) React ecosystem." },
{ "_id" : "junhyukoh/deep-reinforcement-learning-papers", "countall" : 136, "desc" : "A list of recent papers regarding deep reinforcement learning" },
{ "_id" : "shower/shower", "countall" : 66, "desc" : "Shower HTML presentation engine" },
{ "_id" : "codepath/android_guides", "countall" : 72, "desc" : "Extensive Open-Source Guides for Android Developers" },
{ "_id" : "sindresorhus/awesome-npm", "countall" : 132, "desc" : "Awesome npm resources and tips" },
{ "_id" : "arialdomartini/Back-End-Developer-Interview-Questions", "countall" : 180, "desc" : "A list of helpful back-end related questions you can use to interview potential candidates, test yourself or completely ignore." },
{ "_id" : "cxxr/lostpass", "countall" : 89, "desc" : "Pixel-perfect LastPass phishing" },
{ "_id" : "zmywly8866/Android-Develop-Resources", "countall" : 85, "desc" : "汇总优秀的android开发资源，欢迎fork、commit" },
{ "_id" : "gf-rd/blog", "countall" : 210, "desc" : "广发证券技术博客，文章请见issue" },
{ "_id" : "arnicas/interactive-vis-course", "countall" : 50, "desc" : "Repo for U of Miami course on interactive vis." },
{ "_id" : "PaulSec/awesome-sec-talks", "countall" : 197, "desc" : "A collected list of awesome security talks" },
{ "_id" : "thejameskyle/babel-handbook", "countall" : 257, "desc" : ":blue_book: A guided handbook on how to use Babel and how to create plugins for Babel." },
{ "_id" : "liaohuqiu/android-dynamic-load-awesome", "countall" : 68, "desc" : "" },
{ "_id" : "aisuhua/restful-api-design-references", "countall" : 80, "desc" : "RESTful API 设计参考文献列表，可帮助你更加彻底的了解REST风格的接口设计。" },
{ "_id" : "yep/eth-tweet", "countall" : 43, "desc" : "Decentralized Twitter: A microblogging service running on the Ethereum blockchain" },
{ "_id" : "rabbitmq/internals", "countall" : 472, "desc" : "High level architecture overview" },
{ "_id" : "veltman/clmystery", "countall" : 825, "desc" : "A command-line murder mystery" },
{ "_id" : "joanbruna/stat212b", "countall" : 46, "desc" : "Topics Course on Deep Learning UC Berkeley" },
{ "_id" : "relatedcode/ParseAlternatives", "countall" : 314, "desc" : "A collaborative list of Parse alternative backend service providers." },
{ "_id" : "KaimingHe/deep-residual-networks", "countall" : 337, "desc" : "Deep Residual Learning for Image Recognition " },
{ "_id" : "thoughtbot/til", "countall" : 94, "desc" : "Today I Learned" },
{ "_id" : "caesar0301/awesome-public-datasets", "countall" : 2431, "desc" : "An awesome list of high-quality open datasets in public domains (on-going)." },
{ "_id" : "desmond1121/Android-Ptr-Comparison", "countall" : 310, "desc" : "Performance comparison of android \"pull to refresh\" repos in github." },
{ "_id" : "Netflix/osstracker", "countall" : 61, "desc" : "Github organization OSS metrics collector and metrics dashboard" },
{ "_id" : "apple/swift-evolution", "countall" : 694, "desc" : "This maintains proposals for changes and user-visible enhancements to the Swift Programming Language." },
{ "_id" : "dear-github/dear-github", "countall" : 142, "desc" : "An open letter to GitHub from the maintainers of open source projects" },
{ "_id" : "ralphtheninja/open-funding", "countall" : 33, "desc" : "A guide for researching ways of funding full time open source projects." },
{ "_id" : "jobbole/awesome-c-cn", "countall" : 174, "desc" : "C 资源大全中文版，包括了：构建系统、编译器、数据库、加密、初中高的教程/指南、书籍、库等。" },
{ "_id" : "fastlane/screengrab", "countall" : 468, "desc" : "Automated localized screenshots of your Android app on every device" },
{ "_id" : "dhamaniasad/awesome-postgres", "countall" : 491, "desc" : "A curated list of awesome PostgreSQL software, libraries, tools and resources, inspired by awesome-mysql" },
{ "_id" : "Jiar/Awesome-dev-blog-article", "countall" : 63, "desc" : "学习与开发过程中，发现的比较好的一些博客和文章之类的内容，收集着，利人利己，持续更新。" },
{ "_id" : "jeremenichelli/hunt", "countall" : 55, "desc" : "Library to detect when DOM elements become visible and disappear on scroll" },
{ "_id" : "traceglMPL/tracegl", "countall" : 73, "desc" : "TraceGL MPL release" },
{ "_id" : "verlok/lazyload", "countall" : 25, "desc" : "LazyLoad is a fast, lightweight and flexible script to allow you enhance performance on your website by loading images only as they enter (or are about to enter) the viewport or a scrollable area, with best support to the img srcset attribute and to the progressive JPEG image format." },
{ "_id" : "10up/flexibility", "countall" : 181, "desc" : "Use flexbox while supporting older Internet Explorers" },
{ "_id" : "desmond1121/Fresco-Source-Analysis", "countall" : 80, "desc" : "中文的Fresco源码解读" },
{ "_id" : "gravyboat/interviewee-questions", "countall" : 82, "desc" : "Assorted questions to ask during the interview process" },
{ "_id" : "anaibol/awesome-serverless", "countall" : 77, "desc" : "A curated list of awesome services, solutions and ressources for serverless / nobackend applications." },
{ "_id" : "codeinthedark/editor", "countall" : 656, "desc" : "The official Code in the Dark editor" },
{ "_id" : "ReactjsProgram/React-Fundamentals", "countall" : 461, "desc" : "Code for \"React Fundamentals\" videos" },
{ "_id" : "AntBranch/awesome-github", "countall" : 190, "desc" : "收集这个列表，只是为了更好地使用亲爱的GitHub,欢迎提交pr和issue。" },
{ "_id" : "ericelliott/react-things", "countall" : 69, "desc" : "A exploratory list of React ecosystem solutions" },
{ "_id" : "webpro/awesome-dotfiles", "countall" : 45, "desc" : "A curated list of dotfiles resources." },
{ "_id" : "zingchart/awesome-charting", "countall" : 392, "desc" : "A curated list of chart and dataviz resources that developers may find useful." },
{ "_id" : "dingyiming/learn-Js-react", "countall" : 48, "desc" : "学习react" },
{ "_id" : "lagom/lagom", "countall" : 49, "desc" : "Reactive Microservices for the JVM" },
{ "_id" : "bolshchikov/js-must-watch", "countall" : 54, "desc" : "Must-watch videos about javascript" },
{ "_id" : "ride/collaboration-guides", "countall" : 59, "desc" : "some guidelines to make remote collaboration easier at Ride " },
{ "_id" : "ChromeDevTools/awesome-chrome-devtools", "countall" : 356, "desc" : "Awesome tooling and resources in the Chrome DevTools ecosystem" },
{ "_id" : "ziadoz/awesome-php", "countall" : 32, "desc" : "A curated list of amazingly awesome PHP libraries, resources and shiny things." },
{ "_id" : "laravel/internals", "countall" : 66, "desc" : "Issues board used for Laravel internals discussions." },
{ "_id" : "lord63/awesome-python-decorator", "countall" : 60, "desc" : "A curated list of awesome python decorator resources." },
{ "_id" : "cure53/HTTPLeaks", "countall" : 93, "desc" : "HTTPLeaks - All possible ways, a website can leak HTTP requests" },
{ "_id" : "zurb/foundation-emails", "countall" : 69, "desc" : "Quickly create responsive HTML emails that work on any device and client. Even Outlook." },
{ "_id" : "gilbertchen/duplicacy-beta", "countall" : 96, "desc" : "A new generation cloud backup tool " },
{ "_id" : "kakuilan/china_area_mysql", "countall" : 405, "desc" : "中国5级行政区域mysql库" },
{ "_id" : "fcambus/jsemu", "countall" : 84, "desc" : "A list of emulators written in the JavaScript programming language" },
{ "_id" : "kamranahmedse/githunt", "countall" : 61, "desc" : "Chrome Extension - Replace your new tab with trending Github repositories" },
{ "_id" : "ty4z2008/Qix", "countall" : 56, "desc" : "Node.Js、Golang、Machine Learning、PostgreSQL、Deep Learning" },
{ "_id" : "amzn/alexa-avs-raspberry-pi", "countall" : 1817, "desc" : "This project demonstrates how to access and test the Alexa Voice Service using a Java client (running on a Raspberry Pi), and a Node.js server." },
{ "_id" : "ahangchen/How-to-Be-A-Programmer-CN", "countall" : 124, "desc" : "[译]如何做好一枚程序员" },
{ "_id" : "unicodeveloper/awesome-opensource-webapps", "countall" : 58, "desc" : ":house::information_source: Curated list of awesome open source crafted web applications - Learn, Fork, Contribute & Most Importantly Enjoy!" },
{ "_id" : "Gracker/Rss-IT", "countall" : 121, "desc" : "这个项目记录了个人订阅的一些科技人的Blog地址,欢迎大家推荐,一起来完善! 欢迎自荐......" },
{ "_id" : "josephyzhou/producthunt-trending", "countall" : 109, "desc" : "Tracking the product hunt projects, updated daily" },
{ "_id" : "AutumnsWind/Front-end-tutorial", "countall" : 295, "desc" : "S" },
{ "_id" : "reactjs/react-basic", "countall" : 511, "desc" : "A description of the conceptual model of React without implementation burden." },
{ "_id" : "CharonChui/AndroidNote", "countall" : 131, "desc" : "Android study notes." },
{ "_id" : "reactjs/core-notes", "countall" : 97, "desc" : "Weekly meeting notes from the React core team" },
{ "_id" : "JuanitoFatas/what-do-you-call-this-in-ruby", "countall" : 231, "desc" : "Solving the second hard problem in Computer Science." },
{ "_id" : "jobbole/awesome-java-cn", "countall" : 507, "desc" : "Java资源大全中文版，包括开发库、开发工具、网站、博客、微信、微博等，由伯乐在线持续更新。" },
{ "_id" : "markerikson/redux-ecosystem-links", "countall" : 174, "desc" : "A categorized list of Redux-related addons, libraries, and utilities" },
{ "_id" : "Mercateo/component-check", "countall" : 132, "desc" : "A quick introduction to exploring how components can be created in several frameworks." },
{ "_id" : "andris9/mailtrain", "countall" : 767, "desc" : "Self hosted newsletter app" },
{ "_id" : "Dannyzen/openresearch", "countall" : 81, "desc" : "The Open Research Project" },
{ "_id" : "Microsoft/BashOnWindows", "countall" : 121, "desc" : "Issues found within and using Bash on Ubuntu on Windows" },
{ "_id" : "geniuscarrier/webpack-boilerplate", "countall" : 265, "desc" : "A webpack boilerplate in order to quickly build up a production-ready marketing website." },
{ "_id" : "indatawetrust/phoenix-docker", "countall" : 55, "desc" : "Phoenix Framework dockerfile" },
{ "_id" : "programthink/opensource", "countall" : 121, "desc" : "【编程随想】收藏的开源项目清单" },
{ "_id" : "kanemontreuil/portfolio", "countall" : 63, "desc" : "Updated personal portfolio website." },
{ "_id" : "Leo-G/DevopsWiki", "countall" : 251, "desc" : "A wiki of Devops Tools, Tutorials and Scripts" },
{ "_id" : "PalmerAL/min", "countall" : 119, "desc" : "" },
{ "_id" : "laktak/hjson", "countall" : 137, "desc" : "Hjson, the Human JSON" },
{ "_id" : "dbohdan/compilers-targeting-c", "countall" : 70, "desc" : "A list of compilers that can generate C code" },
{ "_id" : "dollabs/pamela", "countall" : 146, "desc" : "Probabalistic Advanced Modeling and Execution Learning Architecture" },
{ "_id" : "bradfrost/frontend-guidelines-questionnaire", "countall" : 138, "desc" : "A one-page questionnaire to help your team establish effective frontend guidelines, so that you can write consistent & cohesive code together." },
{ "_id" : "nhnent/fe.javascript", "countall" : 113, "desc" : "" },
{ "_id" : "DeepMark/deepmark", "countall" : 128, "desc" : "THE Deep Learning Benchmarks" },
{ "_id" : "dustinspecker/awesome-eslint", "countall" : 41, "desc" : "A list of awesome ESLint plugins, configs, etc." },
{ "_id" : "IonicaBizau/gridly", "countall" : 163, "desc" : ":zap: The minimal (~100-170 bytes) grid system for modern browsers." },
{ "_id" : "jobbole/awesome-ios-cn", "countall" : 348, "desc" : "iOS 资源大全中文版，内容包括：框架、组件、测试、Apple Store、SDK、XCode、网站、书籍等" },
{ "_id" : "Junnplus/awesome-python-books", "countall" : 223, "desc" : ":books: Directory of Python books" },
{ "_id" : "X140Yu/Developing-iOS-9-Apps-with-Swift", "countall" : 106, "desc" : "Stanford 公开课，Developing iOS 9 Apps with Swift 字幕翻译" },
{ "_id" : "lipis/flag-icon-css", "countall" : 29, "desc" : ":flags: A collection of all country flags in SVG — plus the CSS for easier integration" },
{ "_id" : "uhub/awesome-c", "countall" : 62, "desc" : "A curated list of awesome C frameworks, libraries and software." },
{ "_id" : "shekhargulati/52-technologies-in-2016", "countall" : 383, "desc" : "Let's learn a new technology every week. A new technology blog every Sunday in 2016." },
{ "_id" : "markerikson/react-redux-links", "countall" : 667, "desc" : "Curated tutorial and resource links I've collected on React, Redux, ES6, and more" },
{ "_id" : "jlcarvalho/InternetSemLimites", "countall" : 97, "desc" : "Repositório que busca catalogar e organizar os provedores de internet que não limitarão o tráfego de dados." },
{ "_id" : "braydie/HowToBeAProgrammer", "countall" : 2384, "desc" : "A guide on how to be a Programmer - originally published by Robert L Read" },
{ "_id" : "kciter/awesome-style-guide", "countall" : 93, "desc" : "A list of awesome:star:style guide." },
{ "_id" : "racaljk/hosts", "countall" : 165, "desc" : ":statue_of_liberty:最新可用的google hosts文件。镜像：" },
{ "_id" : "superdesk/superdesk", "countall" : 90, "desc" : "Superdesk is an end-to-end news creation, production, curation, distribution, and publishing platform." },
{ "_id" : "wingjay/android-open-source-project-cracking", "countall" : 174, "desc" : "通过对流行的优质android开源项目分析、学习、仿写，最终理解，不仅帮你掌握最新的android技术，更能让你理解开源项目的精华之处，这些都是你成为一名高级android developer必不可少的。微信公众号 CoolCoder。Analysis for Popular & Hot Android open-source Applications & Libraries will help you grow into a Senior Android developer. Follow us, do practice in the right and fast way." },
{ "_id" : "giantray/stackoverflow-java-top-qa", "countall" : 212, "desc" : "stackoverflow上Java相关回答整理翻译" },
{ "_id" : "membership/membership.db", "countall" : 181, "desc" : "SQL database schema boilerplate for user accounts, roles and authentication tokens for use in web apps (PostgreSQL, Microsoft SQL Server, Azure SQL Database, LocalDb, SQLite)" },
{ "_id" : "appointmind/fakenames", "countall" : 93, "desc" : "List of names from movies, tv shows and books to be used for testing during development of an application." },
{ "_id" : "jessicard/remote-jobs", "countall" : 55, "desc" : "A list of semi to fully remote-friendly companies in tech" },
{ "_id" : "dbohdan/structured-text-tools", "countall" : 734, "desc" : "A list of command line tools for manipulating structured text data" },
{ "_id" : "akkartik/mu", "countall" : 129, "desc" : "Soul of a tiny new machine for learning programming one-on-one. Tests before syntax; traces over interfaces; rewrite-friendly rather than backwards-compatible." },
{ "_id" : "lfit/itpol", "countall" : 104, "desc" : "Useful IT policies" },
{ "_id" : "jobbole/awesome-mysql-cn", "countall" : 156, "desc" : "MySQL 资源大全中文版，分析工具、备份、性能测试、配置、部署、GUI 等" },
{ "_id" : "sahin/graphdb.io", "countall" : 140, "desc" : "a guide to interesting tools for working with graphdb http://graphdb.io" },
{ "_id" : "sahin/tesla-features", "countall" : 141, "desc" : "" },
{ "_id" : "electron/electron-api-demos", "countall" : 218, "desc" : "Explore the Electron APIs" },
{ "_id" : "php-cds/php-cds", "countall" : 169, "desc" : "PHP Community Driven Standards" },
{ "_id" : "saiprashanths/dl-setup", "countall" : 408, "desc" : "Instructions for setting up the software on your deep learning machine" },
{ "_id" : "jameslk/awesome-falsehoods", "countall" : 78, "desc" : "A curated list of awesome falsehoods programmers believe." },
{ "_id" : "langhua9527/BlackheartedHospital", "countall" : 2388, "desc" : "OpenPower工作组收集汇总的医院开放数据" },
{ "_id" : "FrankFang/best-chinese-front-end-blogs", "countall" : 215, "desc" : "收集优质的中文前端博客" },
{ "_id" : "minbrowser/min", "countall" : 141, "desc" : "A smarter, faster web browser" },
{ "_id" : "pcqpcq/open-source-android-apps", "countall" : 81, "desc" : "Open-Source Android Apps" },
{ "_id" : "jplozi/wastedcores", "countall" : 77, "desc" : "" },
{ "_id" : "dreamlivemeng/androidstudio-plugins", "countall" : 183, "desc" : "Android studio 插件" },
{ "_id" : "phodal/growth-ebook", "countall" : 870, "desc" : "Growth Engineering: The Definitive Guide。全栈增长工程师指南" },
{ "_id" : "Medium/medium-policy", "countall" : 59, "desc" : "Medium’s Policies and Guidelines." },
{ "_id" : "jobbole/awesome-javascript-cn", "countall" : 213, "desc" : "JavaScript 资源大全中文版，内容包括：包管理器、加载器、测试框架、运行器、QA、MVC框架和库、模板引擎等" },
{ "_id" : "phodal/growth-in-action", "countall" : 158, "desc" : "全栈增长工程师实战" },
{ "_id" : "ptresearch/me-disablement", "countall" : 119, "desc" : "" },
{ "_id" : "dxa4481/Pastejacking", "countall" : 735, "desc" : "A demo of overriding what's in a person's clipboard" },
{ "_id" : "picturepan2/spectre", "countall" : 986, "desc" : "Spectre.css - a lightweight, responsive and modern CSS framework." },
{ "_id" : "langhua9527/Hospital", "countall" : 140, "desc" : "OpenPower工作组收集汇总的医院开放数据" },
{ "_id" : "eliangcs/pystock-data", "countall" : 75, "desc" : "US stock market data since 2009" },
{ "_id" : "mindeavor/es-pipeline-operator", "countall" : 96, "desc" : "A proposal for adding the simple-but-useful pipeline operator to JavaScript." },
{ "_id" : "jdsutton/Technical-Interview-Megarepo", "countall" : 96, "desc" : "Study materials for SE/CS technical interviews" },
{ "_id" : "gf-rd/awesome-ng2", "countall" : 150, "desc" : "Angular2 资源大全" },
{ "_id" : "wildbit/postmark-templates", "countall" : 81, "desc" : "Rock-solid email templates for applications." },
{ "_id" : "watson/awesome-computer-history", "countall" : 86, "desc" : "An Awesome List of computer history videos, documentaries and related folklore" },
{ "_id" : "eladnava/mailgen", "countall" : 190, "desc" : "A Node.js package that generates clean, responsive HTML e-mails for sending transactional mail." },
{ "_id" : "wandergis/putian-hospitals", "countall" : 166, "desc" : "根据网络来源的数据地理可视化，在线查看——" },
{ "_id" : "zhouningyi/v-note", "countall" : 38, "desc" : "数据可视化笔记" },
{ "_id" : "fython/BilibiliAPIDocs", "countall" : 71, "desc" : "Bilibili API (thrid-party) Documents 哔哩哔哩开放接口第三方文档" },
{ "_id" : "christiannaths/Redacted-Font", "countall" : 56, "desc" : "Keep your wireframes free of distracting Lorem Ipsum." },
{ "_id" : "vic317yeh/One-Click-to-Be-Pro", "countall" : 1484, "desc" : "A list of the best resources to help you become a pro" },
{ "_id" : "geekan/one-python", "countall" : 119, "desc" : "We don't need a lot of libraries. We just need the best ones. | Unofficial recommended first choice." },
{ "_id" : "atConf/atswift-2016-resources", "countall" : 374, "desc" : "Resource files for atswift conference 2016, including keynote, pdf, source projects or playgrounds. 2016中国Swift开发者大会源文件，包括keynote, pdf 和源工程文件" },
{ "_id" : "terryum/awesome-deep-learning-papers", "countall" : 266, "desc" : "" },
{ "_id" : "olkinn/forest-blue-iTerm", "countall" : 47, "desc" : ":evergreen_tree: A fresh calm color theme for iTerm" },
{ "_id" : "sikuli/sikuli", "countall" : 46, "desc" : "Sikuli's official repository on github. Ask questions or report bugs at http://launchpad.net/sikuli." },
{ "_id" : "openai/requests-for-research", "countall" : 149, "desc" : "A living collection of deep learning problems" },
{ "_id" : "opensourceway/open-decision-framework", "countall" : 111, "desc" : "A community version of the Open Decision Framework" },
{ "_id" : "winter-fall/Bye2015Hi2016", "countall" : 74, "desc" : "" },
{ "_id" : "IPGP/scientific_python_cheat_sheet", "countall" : 64, "desc" : "simple overview of python, numpy, scipy, matplotlib functions that are useful for scientific work" },
{ "_id" : "viljamis/feature.js", "countall" : 773, "desc" : "Feature.js is a fast, simple and lightweight browser feature detection library in 1kb." },
{ "_id" : "cloudfour/drizzle", "countall" : 172, "desc" : "A streamlined tool for developing, documenting and presenting UI pattern libraries." },
{ "_id" : "LogRocket/logrocket", "countall" : 73, "desc" : ":rocket: Record and replay user sessions to fix bugs faster." },
{ "_id" : "vicky002/AlgoWiki", "countall" : 76, "desc" : ":globe_with_meridians: Repository which contains all the links and resources on different topics of Computer Science" },
{ "_id" : "CameloeAnthony/Learning-RecyclerView", "countall" : 134, "desc" : "a collection repository for repositories about recyclerView（RecyclerView大集合）" },
{ "_id" : "yanirs/established-remote", "countall" : 220, "desc" : "A list of established remote companies" },
{ "_id" : "opendigg/awesome-github-vue", "countall" : 100, "desc" : "Vue相关开源项目库汇总" },
{ "_id" : "iOS10-KIT/UI", "countall" : 121, "desc" : "The unofficial iOS 10 UI Kit (Beta)" },
{ "_id" : "chassing/linux-sysadmin-interview-questions", "countall" : 389, "desc" : "Collection of linux sysadmin/devop interview questions" },
{ "_id" : "heynickc/awesome-ddd", "countall" : 129, "desc" : "A curated list of Domain-Driven Design (DDD), Command Query Responsibility Segregation (CQRS), Event Sourcing, and Event Storming resources" },
{ "_id" : "petehunt/react-howto", "countall" : 984, "desc" : "Your guide to the (sometimes overwhelming!) React ecosystem." },
{ "_id" : "nayafia/lemonade-stand", "countall" : 518, "desc" : "A handy guide to financial support for open source" },
{ "_id" : "Microsoft/monaco-editor", "countall" : 1254, "desc" : "A browser based code editor" },
{ "_id" : "farjump/fwtr", "countall" : 108, "desc" : "Open Database of Firmware Test Results" },
{ "_id" : "fanrunqi/AndroidInterview", "countall" : 97, "desc" : "android 面试资料" },
{ "_id" : "github/gov-takedowns", "countall" : 137, "desc" : "Text of government takedown notices as received. GitHub does not endorse or adopt any assertion contained in the following notices." },
{ "_id" : "dotnet/core", "countall" : 194, "desc" : "Home repository for .NET Core" },
{ "_id" : "Miej/GoDeeper", "countall" : 84, "desc" : null },
{ "_id" : "open-source-society/data-science", "countall" : 725, "desc" : ":bar_chart: Path to a free self-taught education in Data Science!" },
{ "_id" : "alibaba/macaca", "countall" : 192, "desc" : "Solution for Automation Test with Ease 一套完整的自动化测试解决方案" },
{ "_id" : "thepracticaldev/orly-full-res", "countall" : 118, "desc" : "Full resolution images of the O RLY book covers made by The Practical Dev" },
{ "_id" : "xxv/android-lifecycle", "countall" : 90, "desc" : "A diagram of the Android Activity / Fragment lifecycle" },
{ "_id" : "linesh-simplicity/translation-spring-mvc-4-documentation", "countall" : 118, "desc" : "Spring MVC 4.2.4 RELEASE 中文文档完整翻译稿" },
{ "_id" : "leemunroe/responsive-html-email-template", "countall" : 51, "desc" : "When all you need is a really simple HTML email template." },
{ "_id" : "leonar15/startup-checklist", "countall" : 580, "desc" : "A checklist for incorporation so you can get back to building your product, fundraising, etc." },
{ "_id" : "AlanCheen/Android-Resources", "countall" : 80, "desc" : "优秀的Android资源收集与整理" },
{ "_id" : "easychen/howto-make-more-money", "countall" : 326, "desc" : "程序员如何优雅的挣零花钱" },
{ "_id" : "shengxinjing/programmer-job-blacklist", "countall" : 2555, "desc" : ":see_no_evil:程序员找工作黑名单，换工作和当技术合伙人需谨慎啊" },
{ "_id" : "servo/servo", "countall" : 315, "desc" : "The Servo Browser Engine" },
{ "_id" : "adam-s/js-interview-review", "countall" : 261, "desc" : "The JS interview review. As I'm reviewing several resources I've bookmarked on JavaScript development, I'll share them here." },
{ "_id" : "rafrex/spa-github-pages", "countall" : 101, "desc" : "host single page apps with github pages" },
{ "_id" : "jacquerie/stop-the-bullshit", "countall" : 68, "desc" : "Blocks websites that publish fake news, and hides their posts on Facebook" },
{ "_id" : "prahladyeri/CuratedLists", "countall" : 139, "desc" : "Curated Lists of various things" },
{ "_id" : "TalAter/awesome-progressive-web-apps", "countall" : 238, "desc" : ":sunrise: A collection of awesome resources for building progressive web apps" },
{ "_id" : "markyun/My-blog", "countall" : 49, "desc" : "马云云在Github的学习片段" },
{ "_id" : "KimberlyMunoz/empathy-in-engineering", "countall" : 53, "desc" : "A curated list of resources for building and promoting more compassionate engineering cultures" },
{ "_id" : "Mila432/Pokemon_Go_API", "countall" : 249, "desc" : null },
{ "_id" : "TalAter/awesome-service-workers", "countall" : 109, "desc" : ":nut_and_bolt: A collection of awesome resources for learning Service Workers" },
{ "_id" : "jxnblk/rebass", "countall" : 341, "desc" : "Configurable React Stateless Functional UI Components" },
{ "_id" : "akullpp/awesome-java", "countall" : 135, "desc" : "A curated list of awesome Java frameworks, libraries and software." },
{ "_id" : "bnb/awesome-hyperterm", "countall" : 152, "desc" : "🖥 Delightful HyperTerm plugins, themes, and resources" },
{ "_id" : "vczero/react-native-lesson", "countall" : 67, "desc" : "React-Native入门指南" },
{ "_id" : "sjchoi86/dl_tutorials", "countall" : 291, "desc" : "Deep learning tutorials (2nd ed.)" },
{ "_id" : "NecronomiconCoding/Pokemon-Go-Bot", "countall" : 65, "desc" : "The biggest Pokemon Go Bot in history. Good Bye!" },
{ "_id" : "estevanmaito/apenas-crie-websites", "countall" : 33, "desc" : "Algumas ideias para sites que você pode construir!" },
{ "_id" : "barretlee/blogChat", "countall" : 82, "desc" : "Chat room source code for Barret Lee's Personal Blog." },
{ "_id" : "usgov/forget-the-king", "countall" : 113, "desc" : "Tired of the king; time to let him know" },
{ "_id" : "amattson21/gitlove", "countall" : 258, "desc" : "me@alexmattson.com" },
{ "_id" : "jesstelford/react-workshop", "countall" : 110, "desc" : "An at-your-own pace practical workshop for absolute beginners to react" },
{ "_id" : "transloadit/uppy", "countall" : 76, "desc" : ":dog: The next open source file uploader for web browsers — a work in progress :warning: :construction:" },
{ "_id" : "thangchung/awesome-dotnet-core", "countall" : 101, "desc" : ":honeybee: A collection of awesome .NET core libraries, tools, frameworks and software" },
{ "_id" : "Xyl2k/TSA-Travel-Sentry-master-keys", "countall" : 204, "desc" : "3D reproduction of TSA Master keys" },
{ "_id" : "secgroundzero/warberry", "countall" : 411, "desc" : "WarBerryPi - Tactical Exploitation" },
{ "_id" : "AHAAAAAAA/PokemonGo-Map", "countall" : 2710, "desc" : "🌏 Live visualization of all the pokemon in your area... and more! (shutdown)" },
{ "_id" : "BrianEstrada/PokeScanner", "countall" : 128, "desc" : "A Scanning tool for Pokemon Go for Android." },
{ "_id" : "warmheartli/ChatBotCourse", "countall" : 215, "desc" : "自己动手做聊天机器人教程" },
{ "_id" : "FallibleInc/security-guide-for-developers", "countall" : 5732, "desc" : "Security Guide for Developers (实用性开发人员安全须知)" },
{ "_id" : "andyb129/AndroidStudioPluginsNPlay", "countall" : 48, "desc" : "A list of cool/useful Android studio plugins" },
{ "_id" : "Afenar/AfenarUI", "countall" : 52, "desc" : "World of Warcraft User Interface" },
{ "_id" : "StanfordPL/stoke-release", "countall" : 167, "desc" : "" },
{ "_id" : "mlpoll/machinematch", "countall" : 50, "desc" : "Machine learning algorithm to connect anonymous accounts to real names" },
{ "_id" : "chibicode/react-functional-css-protips", "countall" : 149, "desc" : ":sunglasses: Functional CSS - The Good, The Bad, and Some Protips for React.js Users" },
{ "_id" : "thednp/kute.js", "countall" : 37, "desc" : "KUTE.js is a native Javascript animation engine featuring great code quality, badass performance, SVG morphing, stroke drawing and 2D & 3D transforms, CSS3 transforms, colors, as well as other CSS3 properties or presentation attributes. " },
{ "_id" : "getify/functional-light-js", "countall" : 133, "desc" : "A book about functional programming in JavaScript." },
{ "_id" : "HQarroum/awesome-iot", "countall" : 98, "desc" : "A curated list of awesome Internet of Things projects and resources." },
{ "_id" : "jiang111/awesome-android-tips", "countall" : 242, "desc" : "some code tips in android" },
{ "_id" : "picnicss/picnic", "countall" : 174, "desc" : ":handbag: A beautiful CSS library to kickstart your projects" },
{ "_id" : "sindresorhus/promise-fun", "countall" : 77, "desc" : "Promise packages, patterns, chat, and tutorials" },
{ "_id" : "AlloyTeam/Mars", "countall" : 331, "desc" : "腾讯移动Web前端知识库" },
{ "_id" : "hedengcheng/tech", "countall" : 516, "desc" : "programming, database, distributed system" },
{ "_id" : "fastlane/match", "countall" : 69, "desc" : "Easily sync your certificates and profiles across your team using git" },
{ "_id" : "datasciencemasters/go", "countall" : 599, "desc" : "The Open Source Data Science Masters" },
{ "_id" : "n1trux/awesome-sysadmin", "countall" : 44, "desc" : "A curated list of amazingly awesome open source sysadmin resources." },
{ "_id" : "kennymkchan/interview-questions-in-javascript", "countall" : 691, "desc" : "A mostly reasonable collection of technical software development interview questions solved in Javascript" },
{ "_id" : "herrbischoff/awesome-osx-command-line", "countall" : 3430, "desc" : "Use your OS X terminal shell to do awesome things." },
{ "_id" : "Dineshs91/gits", "countall" : 59, "desc" : "Get out of apocalypse" },
{ "_id" : "michelpereira/gamesofcoding", "countall" : 290, "desc" : "A curated list of games that can teach you how to learn a programming language." },
{ "_id" : "Jermic/Android-Crack-Tool", "countall" : 155, "desc" : "Android crack tool Just For Mac" },
{ "_id" : "1000ch/grd", "countall" : 557, "desc" : "A CSS grid framework using Flexbox. Only 501 bytes (Gzipped)." },
{ "_id" : "EZLippi/practical-programming-books", "countall" : 94, "desc" : "这里收录比较实用的计算机相关技术书籍，可以在短期之内入门的简单实用教程、一些技术网站以及一些写的比较好的博文，欢迎Fork，你也可以通过Pull Request参与编辑。" },
{ "_id" : "mumuy/data_location", "countall" : 167, "desc" : "Chinese Administrative Division.中国行政区划信息-区划代码数据库" },
{ "_id" : "KhronosGroup/Vulkan-Samples", "countall" : 114, "desc" : "Vulkan sample code" },
{ "_id" : "mortonNex/test90", "countall" : 43, "desc" : "" },
{ "_id" : "kelseyhightower/kubernetes-the-hard-way", "countall" : 1223, "desc" : "Bootstrap Kubernetes the hard way on Google Cloud Platform or Amazon EC2. No scripts." },
{ "_id" : "jlevy/the-art-of-command-line", "countall" : 463, "desc" : "Master the command line, in one page" },
{ "_id" : "huangfangyi/FanXin-based-HuanXin", "countall" : 225, "desc" : "凡信-最强微信仿品" },
{ "_id" : "warmheartli/FullStackDeveloperCourse", "countall" : 194, "desc" : "教你成为全栈工程师" },
{ "_id" : "olivierlacan/keep-a-changelog", "countall" : 32, "desc" : "If you build software, keep a changelog." },
{ "_id" : "codrops/SeatPreview", "countall" : 127, "desc" : "An experimental demo where a 3D perspective preview is shown for a selected seat in a cinema room." },
{ "_id" : "kamranahmedse/design-patterns-for-humans", "countall" : 2690, "desc" : "Design Patterns for Humans™ - An ultra-simplified explanation" },
{ "_id" : "maruos/maruos", "countall" : 187, "desc" : "Welcome to the Maru OS Project!" },
{ "_id" : "haadcode/orbit", "countall" : 103, "desc" : "Distributed, serverless, peer-to-peer chat application on IPFS" },
{ "_id" : "ericdouglas/react-roadmap", "countall" : 131, "desc" : ":link: A curated list of free resources to master React Development :sparkles:" },
{ "_id" : "island205/Single-Page-App-Break", "countall" : 142, "desc" : "单页应用开发权威指南" },
{ "_id" : "bufferapp/android-guidelines", "countall" : 140, "desc" : "Project Guidelines for the Android Buffer App" },
{ "_id" : "raganwald/presentations", "countall" : 166, "desc" : "Conference Talks and Proposals" },
{ "_id" : "jirengu/frontend-interview", "countall" : 132, "desc" : "前端笔试面试题题库" },
{ "_id" : "mzlogin/awesome-adb", "countall" : 547, "desc" : ":lollipop: ADB Usage Complete / ADB 用法大全" },
{ "_id" : "xitu/gold-miner", "countall" : 179, "desc" : "掘金翻译计划，翻译掘金上优质的英文文章" },
{ "_id" : "groob/goviz-frameworks", "countall" : 101, "desc" : "pretty pictures of web frameworks and applications" },
{ "_id" : "tayiorbeii/egghead.io_redux_course_notes", "countall" : 87, "desc" : "Notes (and partial transcription) of Dan Abramov's Redux course videos on http://egghead.io" },
{ "_id" : "onlurking/awesome-infosec", "countall" : 120, "desc" : " A curated list of awesome infosec courses and training resources." },
{ "_id" : "lizhonghui/blog", "countall" : 112, "desc" : "lizhonghui's blog" },
{ "_id" : "mrjoelkemp/awesome-paid-open-source", "countall" : 221, "desc" : "Collection of links around paid/sustainable open source development" },
{ "_id" : "iheanyi/speakers-who-want-a-platform", "countall" : 149, "desc" : "A directory of underrepresented speakers for Q&A panels/conferences/events. No more excuses." },
{ "_id" : "warmheartli/MachineLearningCourse", "countall" : 41, "desc" : "机器学习精简入门教程" },
{ "_id" : "17mon/china_ip_list", "countall" : 99, "desc" : "" },
{ "_id" : "devlinkcn/careTechnologyPartner", "countall" : 117, "desc" : "给技术合伙人准备的一些法律文档，如果你想加入，请联系我： zhufeng@devlink.cn" },
{ "_id" : "struct/mms", "countall" : 131, "desc" : "Modern Memory Safety in C/C++" },
{ "_id" : "LeadDyno/intercooler-js", "countall" : 575, "desc" : "Making AJAX as easy as anchor tags" },
{ "_id" : "christabor/flask_jsondash", "countall" : 915, "desc" : "Build javascript chart dashboards without any front-end code. Uses any json endpoint. JSON config only. Ready to go." },
{ "_id" : "onqtam/awesome-cmake", "countall" : 233, "desc" : "A curated list of awesome CMake scripts, modules, examples and others." },
{ "_id" : "aphyr/distsys-class", "countall" : 367, "desc" : "Class materials for a distributed systems lecture series" },
{ "_id" : "Famolus/awesome-scss", "countall" : 169, "desc" : "🎨 Curated list of awesome Sass and SCSS frameworks, libraries, style guides, articles, and resources." },
{ "_id" : "datasciencebr/serenata-de-amor", "countall" : 144, "desc" : "🕵 Fighting corruption with data and SCIENCE!" },
{ "_id" : "alexazhou/VeryNginx", "countall" : 588, "desc" : " A very powerful and friendly  nginx base on lua-nginx-module( openresty ) which provide WAF, Control Panel, and Dashboards. 功能强大且拥有对人类友好界面的Nginx，提供防火墙，自定义行为，和统计功能" },
{ "_id" : "bloodycoder/githack", "countall" : 866, "desc" : "come on babies.Let's get more stars." },
{ "_id" : "ruijun/Android-Dev-Favorites", "countall" : 224, "desc" : "The repository is Android development favorites, It used to collect the knowledge of Android Development." },
{ "_id" : "timmy3131/design-resource", "countall" : 94, "desc" : "A list of design resources." },
{ "_id" : "smallSohoSolo/android-developer-blog-cn", "countall" : 85, "desc" : "定期翻译Android官方博客" },
{ "_id" : "liuchengxu/git-commit-emoji-cn", "countall" : 58, "desc" : "😁 git commit emoji 使用指南" },
{ "_id" : "RichardLitt/standard-readme", "countall" : 86, "desc" : "Readme Standard Style" },
{ "_id" : "TeamStuQ/skill-map", "countall" : 1400, "desc" : "StuQ 技能图谱" },
{ "_id" : "gztchan/awesome-design", "countall" : 1993, "desc" : ":flags: Best UI/UX Design Resources For Developer & Designer Ever :)" },
{ "_id" : "worrydream/ClimateChange", "countall" : 71, "desc" : "What can a technologist do about climate change? A personal view" },
{ "_id" : "luciotato/golang-notes", "countall" : 324, "desc" : "Notes to understand golang" },
{ "_id" : "greatghoul/remote-working", "countall" : 71, "desc" : "收集整理远程工作相关的资料" },
{ "_id" : "0xAX/linux-insides", "countall" : 677, "desc" : "A little bit about a linux kernel" },
{ "_id" : "bmorelli25/Become-A-Full-Stack-Web-Developer", "countall" : 1894, "desc" : "Free resources for learning Full Stack Web Development" },
{ "_id" : "postlight/awesome-cms", "countall" : 97, "desc" : "📚 A collection of open and closed source Content Management Systems (CMS) for your perusal." },
{ "_id" : "massivedynamic/openftp4", "countall" : 184, "desc" : "A list of all FTP servers in IPv4 that allow anonymous logins." },
{ "_id" : "gostor/awesome-go-storage", "countall" : 160, "desc" : "A curated list of awesome Go storage projects and libraries" },
{ "_id" : "sfermigier/awesome-functional-python", "countall" : 63, "desc" : null },
{ "_id" : "thibmaek/awesome-raspberrypi", "countall" : 657, "desc" : "A curated list of awesome Raspberry Pi tools, projects, images and resources" },
{ "_id" : "fivefilters/block-ads", "countall" : 52, "desc" : "Web page to test ad blocking and encourage use of blockers." },
{ "_id" : "jgthms/web-design-in-4-minutes", "countall" : 842, "desc" : "Learn basics of web design in 4 minutes" },
{ "_id" : "mandatoryprogrammer/NorthKoreaDNSLeak", "countall" : 355, "desc" : "Snapshot of North Korea's DNS data taken from zone transfers." },
{ "_id" : "sindresorhus/ponyfill", "countall" : 208, "desc" : "🦄 Like polyfill but with pony pureness" },
{ "_id" : "gavindinubilo/jam-api", "countall" : 432, "desc" : "Parse web pages using CSS query selectors" },
{ "_id" : "RyanZim/awesome-npm-scripts", "countall" : 92, "desc" : "Everything awesome related to npm scripts and using npm as a build tool." },
{ "_id" : "kjw0612/awesome-rnn", "countall" : 242, "desc" : "Recurrent Neural Network - A curated list of resources dedicated to RNN" },
{ "_id" : "AllThingsSmitty/must-watch-javascript", "countall" : 196, "desc" : "A useful list of must-watch talks about JavaScript" },
{ "_id" : "GeekLiB/Lee-VR-Source", "countall" : 176, "desc" : "VR developers necessary resources(VR 开发者必备资源汇总)" },
{ "_id" : "kendricktan/non-overwhelming-machine-learning", "countall" : 61, "desc" : "A (non overwhelming) list of Machine Learning resources for beginners" },
{ "_id" : "devspace/awesome-github-templates", "countall" : 88, "desc" : ":octocat: Curated list of GitHub Issues and Pull Requests templates" },
{ "_id" : "Nax/longflow-manifesto", "countall" : 325, "desc" : ":coffee: The longflow manifesto" },
{ "_id" : "amattson21/gitjob", "countall" : 7830, "desc" : "me@alexmattson.com" },
{ "_id" : "ryanhoo/make-icons", "countall" : 61, "desc" : "A demonstration for practicing Sketch skills by following the tutorial #makeicons step by step." },
{ "_id" : "putaoshu/fe-dev-bookmarks", "countall" : 63, "desc" : "A list of frontend development resources collected." },
{ "_id" : "stoeffel/awesome-fp-js", "countall" : 142, "desc" : ":sunglasses: A curated list of awesome functional programming stuff in js" },
{ "_id" : "alebcay/awesome-shell", "countall" : 118, "desc" : "A curated list of awesome command-line frameworks, toolkits, guides and gizmos. Inspired by awesome-php." },
{ "_id" : "gophish/gophish", "countall" : 237, "desc" : "Open-Source Phishing Toolkit" },
{ "_id" : "DynamicCocoa/DynamicCocoa", "countall" : 363, "desc" : "A framework for running Cocoa code dynamically." },
{ "_id" : "danluu/debugging-stories", "countall" : 177, "desc" : "A collection of debugging stories. PRs welcome :-)" },
{ "_id" : "allenwong/MakeIconsWithSketch", "countall" : 107, "desc" : "Simple tutorials about how to make icons with Sketch. " },
{ "_id" : "Microsoft/api-guidelines", "countall" : 2193, "desc" : "Microsoft REST API Guidelines" },
{ "_id" : "nothings/single_file_libs", "countall" : 1015, "desc" : "List of single-file C/C++ libraries." },
{ "_id" : "zer0n/deepframeworks", "countall" : 133, "desc" : "Evaluation of Deep Learning Frameworks" },
{ "_id" : "zmywly8866/Worth-Reading-the-Android-technical-articles", "countall" : 133, "desc" : "值得阅读的android技术文章" },
{ "_id" : "VoLuong/Begin-Latex-in-minutes", "countall" : 431, "desc" : ":bowtie: Brief Intro to LaTeX for beginners that helps you use LaTeX with ease. Comments and Contributions are welcomed :thumbsup: " },
{ "_id" : "zrispo/wick", "countall" : 75, "desc" : "The Internet's free and open source multimedia creation suite" },
{ "_id" : "ruanyf/document-style-guide", "countall" : 134, "desc" : "中文技术文档的写作规范" },
{ "_id" : "Symfonisti/awesome-symfony-education", "countall" : 24, "desc" : "Useful sources around Symfony - articles, series and books (not Bundles)" },
{ "_id" : "AllThingsSmitty/css-protips", "countall" : 1508, "desc" : "A collection of tips to help take your CSS skills pro" },
{ "_id" : "timarney/react-faq", "countall" : 101, "desc" : "A collection of links to help answer your questions about React.js" },
{ "_id" : "engineerapart/TheRemoteFreelancer", "countall" : 1006, "desc" : "Listing of community-curated resources to find topical remote freelance & contract work for software developers, web designers, and more!" },
{ "_id" : "zazaalaza/awesome-ideation-tools", "countall" : 38, "desc" : "Problem solving and idea generation tools" },
{ "_id" : "vicky002/TheUltimateInternshipGuide", "countall" : 31, "desc" : "Best guide for internship." },
{ "_id" : "JosPolfliet/awesome-datascience-ideas", "countall" : 30, "desc" : "A list of awesome and proven data science use cases and applications" },
{ "_id" : "rubyomr-preview/rubyomr-preview", "countall" : 89, "desc" : "Ruby+OMR Technology Preview" },
{ "_id" : "pirate/sites-using-cloudflare", "countall" : 1201, "desc" : ":broken_heart: List of domains using Cloudflare DNS (potentially affected by the CloudBleed HTTPS traffic leak)" },
{ "_id" : "yuguo/bat-internal-referral", "countall" : 104, "desc" : "BAT等国内互联网公司内推" },
{ "_id" : "danluu/post-mortems", "countall" : 156, "desc" : "A collection of postmortems. Pull requests welcome, although I'm way behind on merging :-)" },
{ "_id" : "micromata/awesome-javascript-learning", "countall" : 70, "desc" : "A tiny list limited to the best JavaScript Learning Resources" },
{ "_id" : "mjavascript/practical-es6", "countall" : 451, "desc" : "🏊 A practical dive into ES6 and maintainable JavaScript modules" },
{ "_id" : "BruceDone/awesome-crawler", "countall" : 306, "desc" : "A collection of awesome web crawler,spider in different languages" },
{ "_id" : "lukasz-madon/awesome-remote-job", "countall" : 579, "desc" : "A curated list of awesome remote jobs and resources. Inspired by https://github.com/vinta/awesome-python" },
{ "_id" : "kosinix/grafika", "countall" : 104, "desc" : "An image processing library for PHP" },
{ "_id" : "jobbole/awesome-machine-learning-cn", "countall" : 59, "desc" : "机器学习资源大全中文版，包括机器学习领域的框架、库以及软件" },
{ "_id" : "Pranav0212/HHCodingInterviewPrep", "countall" : 38, "desc" : "Preparation for coding interviews" },
{ "_id" : "dotnet/csharplang", "countall" : 189, "desc" : "The official repo for the design of the C# programming language" },
{ "_id" : "material-foundation/material-remixer", "countall" : 382, "desc" : "A set of cross-platform libraries and protocols to allow the sharing of design values and live refinement of apps during the development process." },
{ "_id" : "lelylan/lelylan", "countall" : 158, "desc" : "Open Source Lightweight Microservices Architecture for the Internet of Things. For developers." },
{ "_id" : "ijry/lyicon", "countall" : 182, "desc" : "兼容fa的图标库" },
{ "_id" : "perspectivesonatheme/patterns", "countall" : 93, "desc" : "A framework of abstract patterns" },
{ "_id" : "jobbole/awesome-programming-books", "countall" : 125, "desc" : "经典编程书籍大全，涵盖：计算机系统与网络、系统架构、算法与数据结构、前端开发、后端开发、移动开发、数据库、测试、项目与团队、程序员职业修炼、求职面试等" },
{ "_id" : "aymericdamien/TopDeepLearning", "countall" : 1084, "desc" : "A list of popular github projects related to deep learning" },
{ "_id" : "geerlingguy/mac-dev-playbook", "countall" : 372, "desc" : "Mac setup and configuration via Ansible." },
{ "_id" : "VoLuong/Master-Latex-in-minutes", "countall" : 203, "desc" : ":bowtie: Brief Intro to LaTeX for beginners that helps you use LaTeX with ease. Comments and Contributions are welcomed :thumbsup: " },
{ "_id" : "open-power-workgroup/Hospital", "countall" : 407, "desc" : "OpenPower工作组收集汇总的医院开放数据" },
{ "_id" : "coursera-dl/coursera-dl", "countall" : 126, "desc" : "Script for downloading Coursera.org videos and naming them." },
{ "_id" : "nushackers/notes-to-cs-freshmen-from-the-future", "countall" : 81, "desc" : "Notes to (NUS) Computer Science Freshmen, From The Future (Original by @ejamesc)" },
{ "_id" : "brettchalupa/developer-interview-questions", "countall" : 32, "desc" : "Questions to ask when interviewing for a software developer position" },
{ "_id" : "deptofdefense/code.mil", "countall" : 578, "desc" : "An experiment in open source" },
{ "_id" : "vertexclique/tokamak", "countall" : 206, "desc" : "Fusion Reactor for Rust - Atom Rust IDE" },
{ "_id" : "gopherchina/conference", "countall" : 278, "desc" : "" },
{ "_id" : "dirtycow/dirtycow.github.io", "countall" : 366, "desc" : "Dirty COW" },
{ "_id" : "googlesamples/android-architecture", "countall" : 1878, "desc" : "A collection of samples to discuss and showcase different architectural tools and patterns for Android apps." },
{ "_id" : "ManrajGrover/SingleDivProject", "countall" : 384, "desc" : "One <div>. Many possibilities." },
{ "_id" : "joereynolds/what-to-code", "countall" : 54, "desc" : "Ideas for things to program" },
{ "_id" : "sqreen/awesome-nodejs-projects", "countall" : 590, "desc" : "Curated list of awesome open-source applications made with Node.js" },
{ "_id" : "multunus/first-contributions", "countall" : 74, "desc" : "Yet another project to get beginners contributing to open source 🔰🚀 " },
{ "_id" : "jareware/css-architecture", "countall" : 174, "desc" : "8 simple rules for a robust, scalable CSS architecture" },
{ "_id" : "opendigg/awesome-github-wechat-weapp", "countall" : 137, "desc" : "微信小程序开源项目库汇总" },
{ "_id" : "github/game-off-2016", "countall" : 117, "desc" : "GitHub's month-long game jam :video_game: November 2016" },
{ "_id" : "AoDevBlue/MaterialValues", "countall" : 95, "desc" : "An Android library for material design values" },
{ "_id" : "vermont42/Podcasts", "countall" : 80, "desc" : "This is a list of podcasts of interest to iOS developers." },
{ "_id" : "leereilly/games", "countall" : 1658, "desc" : ":video_game: A list of popular/awesome videos games, add-ons, maps, etc. hosted on GitHub. Any genre. Any platform. Any engine." },
{ "_id" : "korneliakobiela/BHSite", "countall" : 69, "desc" : "BIOHeretics website project" },
{ "_id" : "shimohq/chinese-programmer-wrong-pronunciation", "countall" : 1104, "desc" : "中国程序员容易发音错误的单词" },
{ "_id" : "ESWAT/john-carmack-plan-archive", "countall" : 173, "desc" : "Collection of John Carmack’s .plan files." },
{ "_id" : "coodict/javascript-in-one-pic", "countall" : 66, "desc" : "Learn javascript in one picture." },
{ "_id" : "opendatajson/factbook.json", "countall" : 83, "desc" : "World Factbook Country Profiles in JSON  - Free Open Public Domain Data - No API Key Required ;-)" },
{ "_id" : "dhamaniasad/HeadlessBrowsers", "countall" : 754, "desc" : "A list of (almost) all headless web browsers in existence" },
{ "_id" : "sbrugman/deep-learning-papers", "countall" : 547, "desc" : "Papers about deep learning ordered by task, date. Current state-of-the-art papers are labelled." },
{ "_id" : "dwango/yakisoba-sauce", "countall" : 47, "desc" : "Open source recipe of yakisoba-sauces for chokaigi 2016" },
{ "_id" : "SKTBrain/awesome-starcraftAI", "countall" : 76, "desc" : "A curated list of resources dedicated to StarCraft AI." },
{ "_id" : "madhugb/Global-Task-Exchange-Protocol", "countall" : 38, "desc" : "Micro organizations are becoming mainstream, people work with multiple organization to complete one project. All the task management systems fail in this case. Using GTEP you can exchange tasks like Email." },
{ "_id" : "Yixiaohan/show-me-the-code", "countall" : 56, "desc" : "Python 练习册，每天一个小程序" },
{ "_id" : "adam-s/facebook-pixel-guide", "countall" : 80, "desc" : "A guide to using Facebook pixel for efficient ad campaigns" },
{ "_id" : "Wscats/Good-text-Share", "countall" : 70, "desc" : ":smiley_cat:猫的前端回忆 These share data are from my usual work and learning，hoping to help you，If you like you can star" },
{ "_id" : "AnthonyCalandra/modern-cpp-features", "countall" : 1086, "desc" : "A cheatsheet of modern C++ language and library features." },
{ "_id" : "awslabs/serverless-application-model", "countall" : 46, "desc" : "AWS Serverless Application Model (AWS SAM) prescribes rules for expressing Serverless applications on AWS." },
{ "_id" : "Hack-with-Github/Awesome-Hacking", "countall" : 1581, "desc" : "A collection of various awesome lists for hackers, pentesters and security researchers" },
{ "_id" : "GitAlias/gitalias", "countall" : 149, "desc" : "Git alias commands for faster easier version control" },
{ "_id" : "space10-community/conversational-form", "countall" : 569, "desc" : "Turning web forms into conversations" },
{ "_id" : "taylorham/react-conf-17-videos", "countall" : 94, "desc" : "Find that one presentation you missed!" },
{ "_id" : "BoxFactura/pulltorefresh.js", "countall" : 227, "desc" : "A quick and powerful plugin for your pull-to-refresh needs in your webapp." },
{ "_id" : "apple/swift-protobuf-plugin", "countall" : 459, "desc" : "Moved to apple/swift-protobuf" },
{ "_id" : "webpack-china/awesome-webpack-cn", "countall" : 216, "desc" : "webpack优秀中文文章" },
{ "_id" : "amitkaps/visdown", "countall" : 130, "desc" : "Visualisation Markdown" },
{ "_id" : "zachlatta/sshtron", "countall" : 43, "desc" : "Play Tron over SSH" },
{ "_id" : "jtyjty99999/mobileTech", "countall" : 45, "desc" : "A useful tools or tips list for mobile web application developing" },
{ "_id" : "Developer-Y/cs-video-courses", "countall" : 2711, "desc" : "List of Computer Science courses with video lectures." },
{ "_id" : "javascript-society/javascript-path", "countall" : 46, "desc" : ":books: List of books to master JavaScript Development :rocket:" },
{ "_id" : "fkomauli/riforma-costituzionale", "countall" : 98, "desc" : "Disposizioni per il superamento del bicameralismo paritario, la riduzione del numero dei parlamentari, il contenimento dei costi di funzionamento delle istituzioni, la soppressione del CNEL e la revisione del titolo V della parte II della Costituzione." },
{ "_id" : "ryanhoo/Android-Proficiency-Exercise", "countall" : 75, "desc" : "Impress me" },
{ "_id" : "pmanizio/linksuteis", "countall" : 56, "desc" : "Alguns links úteis para Desenvolvedores Web" },
{ "_id" : "perfs/audits", "countall" : 114, "desc" : ":rocket: Performance audits for the web: sites, webapps, JS frameworks and libraries." },
{ "_id" : "WeMobileDev/article", "countall" : 199, "desc" : "articles by WeChat Mobile Development Team" },
{ "_id" : "googlei18n/noto-fonts", "countall" : 155, "desc" : " Noto fonts, except for CJK and emoji" },
{ "_id" : "stone0090/javascript-lessons", "countall" : 109, "desc" : "本课程之所以叫做《JavaScript 闯关记》，是因为部分章节精心设计了挑战关卡，通过提供更多的实战机会，让大家可以循序渐进地、有目的地、有挑战地开展学习。" },
{ "_id" : "ace-lol/Ace", "countall" : 41, "desc" : ":sparkles: Ace - Alpha Client Enhancer" },
{ "_id" : "vczero/react-native-lession", "countall" : 91, "desc" : "React-Native入门指南" },
{ "_id" : "ElemeFE/restc", "countall" : 415, "desc" : "A server-side middleware to visualize REST requests." },
{ "_id" : "anders94/blockchain-demo", "countall" : 196, "desc" : "A web-based demonstration of blockchain concepts." },
{ "_id" : "chrislgarry/awesome-machine-learning", "countall" : 64, "desc" : "A curated list of awesome Machine Learning frameworks, libraries and software." },
{ "_id" : "sobotka/filmic-blender", "countall" : 102, "desc" : "Filmic View and Look Transformations for Blender" },
{ "_id" : "SmartisanTech/android", "countall" : 1044, "desc" : "Smartisan open source code for full build.(repo manifest xml)" },
{ "_id" : "alex/what-happens-when", "countall" : 525, "desc" : "An attempt to answer the age old interview question \"What happens when you type google.com into your browser and press enter?\"" },
{ "_id" : "stefanbuck/awesome-browser-extensions-for-github", "countall" : 88, "desc" : "A collection of awesome browser extensions for GitHub." },
{ "_id" : "pstadler/keybase-gpg-github", "countall" : 439, "desc" : "Step-by-step guide on how to create a GPG key on keybase.io, adding it to a local GPG setup and use it with Git and GitHub." },
{ "_id" : "mightyCrow/dont-go", "countall" : 56, "desc" : null },
{ "_id" : "GreatStars/AwesomeStars", "countall" : 197, "desc" : "make much stars, forks, watches if you want" },
{ "_id" : "facebook/jsx", "countall" : 59, "desc" : "The JSX specification is a XML-like syntax extension to ECMAScript." },
{ "_id" : "worldligang/CodeReading", "countall" : 264, "desc" : null },
{ "_id" : "linkedin/swift-style-guide", "countall" : 134, "desc" : "LinkedIn's Official Swift Style Guide" },
{ "_id" : "jeromeetienne/AR.js", "countall" : 564, "desc" : "Efficient Augmented Reality for the Web using ARToolKit - 60fps on mobile!" },
{ "_id" : "255kb/stack-on-a-budget", "countall" : 820, "desc" : "A collection of services with great free tiers for developers on a budget" },
{ "_id" : "gpakosz/.tmux", "countall" : 104, "desc" : "Oh My Tmux! My pretty + versatile self-contained tmux configuration" },
{ "_id" : "jgthms/css-reference", "countall" : 955, "desc" : "CSS Reference: a free visual guide to the most popular CSS properties" },
{ "_id" : "akic4op4/GNE", "countall" : 101, "desc" : "준비된 한국형 언어" },
{ "_id" : "abhishekbanthia/Public-APIs", "countall" : 879, "desc" : "📚 A public list of APIs from round the web." },
{ "_id" : "MaximAbramchuck/awesome-interview-questions", "countall" : 813, "desc" : ":octocat: A curated awesome list of lists of interview questions. Feel free to contribute! :mortar_board: " },
{ "_id" : "github/swift-style-guide", "countall" : 394, "desc" : "Style guide & coding conventions for Swift projects" },
{ "_id" : "facebookincubator/react-vr", "countall" : 332, "desc" : "Issues-only repo for React VR - a React Native platform to run 3D and WebVR content." },
{ "_id" : "github-beta/unity-preview", "countall" : 163, "desc" : "GitHub for Unity, the Preview!" },
{ "_id" : "fuchsia-mirror/fuchsia", "countall" : 80, "desc" : null },
{ "_id" : "j-delaney/easy-application", "countall" : 688, "desc" : "382 software engineering companies that are easy to apply to" },
{ "_id" : "gdgbeijing/devfest2016", "countall" : 147, "desc" : "http://chinagdg.org/2016-devfest-beijing/" },
{ "_id" : "heyalexej/awesome-images", "countall" : 55, "desc" : "A curated list of amazingly awesome free (stock) photo resources inspired by all the other awesomes." },
{ "_id" : "a0viedo/demystifying-js-engines", "countall" : 665, "desc" : "A list of resources about JavaScript engines" },
{ "_id" : "wesbos/JavaScript30", "countall" : 155, "desc" : "30 Day Vanilla JS Challenge" },
{ "_id" : "bevacqua/es6", "countall" : 522, "desc" : ":star2: ES6 Overview in 350 Bullet Points" },
{ "_id" : "phodal/ideabook", "countall" : 442, "desc" : "一个全栈增长工程师的练手项目集. A Growth Engineering Idea in Action." },
{ "_id" : "andrew--r/channels", "countall" : 798, "desc" : "A collection of useful YouTube channels for javascript developers and web designers" },
{ "_id" : "onmyway133/fantastic-ios-animation", "countall" : 622, "desc" : ":umbrella: A collection of iOS animation repos" },
{ "_id" : "peerfact/peerfact.github.io", "countall" : 45, "desc" : "PeerFact public website and domain registry. See https://github.com/peerfact/extension for the actual plugin." },
{ "_id" : "Microsoft/language-server-protocol", "countall" : 88, "desc" : "Defines a common protocol for language servers." },
{ "_id" : "thepracticaldev/dev.to", "countall" : 104, "desc" : "Where programmers share ideas and help each other grow" },
{ "_id" : "NECROBOTIO/NecroBot", "countall" : 213, "desc" : "The biggest Pokemon Go Bot in history. Good Bye!" },
{ "_id" : "ReactjsProgram/react-fundamentals-curriculum", "countall" : 415, "desc" : "Curriculum for React.js Program's \"React Fundamentals\" course" },
{ "_id" : "TIBCOSoftware/flogo", "countall" : 84, "desc" : "Project Flogo" },
{ "_id" : "bnb/awesome-hyper", "countall" : 123, "desc" : "🖥 Delightful Hyper plugins, themes, and resources" },
{ "_id" : "open-source-society/computer-science", "countall" : 1007, "desc" : ":mortar_board: Path to a free self-taught education in Computer Science!" },
{ "_id" : "asd0102433/blog", "countall" : 51, "desc" : "凹凸的博客" },
{ "_id" : "neveragaindottech/neveragaindottech.github.io", "countall" : 236, "desc" : "Source files for the neveragain.tech site" },
{ "_id" : "wentin/ResponsifyJS", "countall" : 112, "desc" : "A jquery plugin that makes images truly responsive, without sacrificing anyone's face. Give it more stars!" },
{ "_id" : "delapuente/service-workers-101", "countall" : 133, "desc" : "An infographic to summarize the most important parts of the Service Workers' API" },
{ "_id" : "EderSantana/awesomeMLmath", "countall" : 60, "desc" : "Curated list to learn the math basics for machine learning" },
{ "_id" : "samihasan/eskendereyya", "countall" : 44, "desc" : "Eskéndereyya: Learn how to read and write Arabic in less than 60 minutes" },
{ "_id" : "xcatliu/typescript-tutorial", "countall" : 109, "desc" : "TypeScript 入门教程" },
{ "_id" : "keonkim/awesome-bits", "countall" : 298, "desc" : ":computer: A curated list of awesome bitwise operations and tricks" },
{ "_id" : "dear-apple/dear-apple", "countall" : 67, "desc" : "An open 📧 to Apple from developers that work in a daily basis with their tools ⚒" },
{ "_id" : "devlinkcn/ppts_for_idev2016", "countall" : 63, "desc" : "iDev 2016 全平台开发者大会 PPTs" },
{ "_id" : "ipmjs/ipmjs", "countall" : 102, "desc" : "Immutable Package Manager" },
{ "_id" : "rstacruz/webpack-tricks", "countall" : 665, "desc" : "Tips and tricks in using Webpack" },
{ "_id" : "Youpinadi/netflix-categories", "countall" : 159, "desc" : "Netflix links to all hidden categories" },
{ "_id" : "hypotext/notation", "countall" : 219, "desc" : "Collection of quotes on interesting notations & how they affect thought." },
{ "_id" : "una/YouMightNotNeedJS", "countall" : 512, "desc" : null },
{ "_id" : "OWASP/DevGuide", "countall" : 184, "desc" : "The OWASP Guide" },
{ "_id" : "uikit/uikit", "countall" : 88, "desc" : "A lightweight and modular front-end framework for developing fast and powerful web interfaces." },
{ "_id" : "d3viant0ne/awesome-webpack", "countall" : 79, "desc" : "A curated list of awesome Webpack resources, libraries and tools" },
{ "_id" : "dustinvtran/ml-videos", "countall" : 280, "desc" : "A collection of video resources for machine learning" },
{ "_id" : "zhangqianhui/AdversarialNetsPapers", "countall" : 92, "desc" : "The classical papers and codes about generative adversarial nets " },
{ "_id" : "ggomaeng/better-developer-quotes", "countall" : 152, "desc" : "💡 A compilation of answers I received from other developers when I asked them--\"How do I become a better developer?\"" },
{ "_id" : "joebew42/study-path", "countall" : 365, "desc" : "A study path about Clean Code, TDD, Legacy Code, Refactoring and IDD" },
{ "_id" : "adamsitnik/awesome-dot-net-performance", "countall" : 232, "desc" : "A curated list of awesome .NET Performance books, courses, trainings, conference talks, blogs and most inspiring open source contributors. Inspired by awesome-... stuff." },
{ "_id" : "wasabeef/awesome-android-ui", "countall" : 249, "desc" : "A curated list of awesome Android UI/UX libraries" },
{ "_id" : "samdutton/simpl", "countall" : 129, "desc" : "Simplest possible examples of HTML, CSS and Javascript:" },
{ "_id" : "amfe/article", "countall" : 175, "desc" : "" },
{ "_id" : "passy/awesome-recursion-schemes", "countall" : 65, "desc" : "Resources for learning and using recursion schemes." },
{ "_id" : "borisuvarov/python-cookbook-ru", "countall" : 45, "desc" : "Python Cookbook by David Beazley, Brian K. Jones (russian translate)" },
{ "_id" : "propwnadmin/propwnadmin.github.io", "countall" : 301, "desc" : "ProPwn Backup" },
{ "_id" : "taizilongxu/interview_python", "countall" : 212, "desc" : "关于Python的面试题" },
{ "_id" : "enddo/android-security-awesome", "countall" : 150, "desc" : "A collection of android security related resources" },
{ "_id" : "hyperledger/hyperledger", "countall" : 107, "desc" : "Hyperledger Project is a new Collaborative Project at The Linux Foundation. The technical community is just getting started and will be adding code to the repository in the coming weeks. Check hyperledger.org for more information about joining the mailing lists and participating in the conversations." },
{ "_id" : "Droogans/unmaintainable-code", "countall" : 1565, "desc" : "A more maintainable, easier to share version of the infamous http://mindprod.com/jgloss/unmain.html" },
{ "_id" : "skyline75489/what-happens-when-zh_CN", "countall" : 335, "desc" : "What-happens-when 的中文翻译，原仓库 https://github.com/alex/what-happens-when" },
{ "_id" : "yoshuawuyts/tiny-guide-to-non-fancy-node", "countall" : 323, "desc" : "A tiny guide to non fancy, high-value Node.js things" },
{ "_id" : "UKHomeOffice/posters", "countall" : 69, "desc" : "Home Office Digital repository of posters covering different topics - research, access needs, accessibility, design." },
{ "_id" : "sindresorhus/awesome", "countall" : 1009, "desc" : ":sunglasses: Curated list of awesome lists" },
{ "_id" : "zangqilong198812/CodeReviewKeynote", "countall" : 60, "desc" : "" },
{ "_id" : "HollyAdele/awesome-programming-for-kids", "countall" : 58, "desc" : "A curated list of resources for teaching kids programming. " },
{ "_id" : "mcxiaoke/RxDocs", "countall" : 99, "desc" : "Rx和RxJava文档中文翻译项目" },
{ "_id" : "xirong/my-git", "countall" : 90, "desc" : "Individual collecting material of learning git（有关 git 的学习资料）" },
{ "_id" : "ethan-funny/explore-python", "countall" : 339, "desc" : ":green_book: The Beauty of Python Programming." },
{ "_id" : "tastejs/awesome-app-ideas", "countall" : 124, "desc" : "List of awesome app ideas" },
{ "_id" : "mortonNex/test04", "countall" : 42, "desc" : "" },
{ "_id" : "creart/ChunkNorris", "countall" : 101, "desc" : "The most powerful Minecraft anticheat." },
{ "_id" : "sangupta/ps", "countall" : 452, "desc" : "Problem Solving" },
{ "_id" : "amaas/stanford_dl_ex", "countall" : 98, "desc" : "Programming exercises for the Stanford Unsupervised Feature Learning and Deep Learning Tutorial" },
{ "_id" : "ruiqimao/keyboard-pcb-guide", "countall" : 131, "desc" : "Guide on how to design keyboard PCBs with KiCad" },
{ "_id" : "Morhaus/facebook-sixth-sense", "countall" : 221, "desc" : "A Chrome extension that lets you know when your friends start writing to you on Facebook" },
{ "_id" : "alivebao/clean-code-js", "countall" : 40, "desc" : "JavaScript风格指南" },
{ "_id" : "1ppm/1ppmLog", "countall" : 266, "desc" : "Release one side project per month, log your results here!" },
{ "_id" : "tayiorbeii/egghead.io_idiomatic_redux_course_notes", "countall" : 80, "desc" : "Notes from Dan Abramov's Idiomatic Redux course on Egghead.io" },
{ "_id" : "antontarasenko/smq", "countall" : 704, "desc" : "A collection of SQL queries to social media datasets." },
{ "_id" : "chromium/badssl.com", "countall" : 91, "desc" : ":lock: Memorable site for testing clients against bad SSL configs." },
{ "_id" : "wildbit/mailmason", "countall" : 76, "desc" : "A complete toolset to streamline building and updating a set of consistent transactional emails." },
{ "_id" : "mortonNex/test06", "countall" : 100, "desc" : "" },
{ "_id" : "LineageOS/android", "countall" : 95, "desc" : "Misc Android stuff" },
{ "_id" : "MunGell/awesome-for-beginners", "countall" : 100, "desc" : "A list of awesome beginners-friendly projects." },
{ "_id" : "melnik909/frontend-whitelist", "countall" : 176, "desc" : "Frontend WhiteList — это список полезных ресурсов для разработчиков интерфейсов" },
{ "_id" : "igoradamenko/awsm.css", "countall" : 97, "desc" : "Simple CSS library for semantic HTML markup" },
{ "_id" : "BraisedCakes/tank", "countall" : 202, "desc" : "h5小游戏" },
{ "_id" : "google/material-design-lite", "countall" : 193, "desc" : "Material Design Lite Components in HTML/CSS/JS" },
{ "_id" : "in28minutes/java-best-practices", "countall" : 65, "desc" : "Best practices in Coding, Designing and Architecting Java Applications" },
{ "_id" : "jobbole/awesome-design-cn", "countall" : 54, "desc" : "设计师资源大全，包含：ICON图标、Logo设计、PhotoShop插件、交互设计工具、流程图、线框图/原型图、设计博客等" },
{ "_id" : "JustFollowUs/Machine-Learning", "countall" : 129, "desc" : null },
{ "_id" : "danklammer/bytesize-icons", "countall" : 325, "desc" : "Tiny style-controlled SVG iconset" },
{ "_id" : "iuap-design/tinper-bee", "countall" : 196, "desc" : "ui components built with react.js - 基于 react.js 和 iuap design 设计语言实现的前端组件库" },
{ "_id" : "ValveSoftware/steamlink-sdk", "countall" : 261, "desc" : "An SDK for creating native Steam Link applications" },
{ "_id" : "dargaCode/LogicAndCodingGames", "countall" : 120, "desc" : "(Markdown) - A list of programming-related games I'd like to try" },
{ "_id" : "mamal72/star-bomb", "countall" : 100, "desc" : "This repo stars are SUPER ULTRA REAL. Don't mess with me. :|" },
{ "_id" : "HiFaraz/node-playbook", "countall" : 458, "desc" : "Get started fast with Node.js" },
{ "_id" : "dakaraphi/development-resources", "countall" : 48, "desc" : "Collection of useful development resources" },
{ "_id" : "mortonNex/wangyijun", "countall" : 62, "desc" : "" },
{ "_id" : "barretlee/performance-column", "countall" : 247, "desc" : "🚅 性能专栏（Performance Column）" },
{ "_id" : "poteto/elixirconf-2016", "countall" : 161, "desc" : "ElixirConf 2016 summary" },
{ "_id" : "MDCC2016/Android-Session-Slides", "countall" : 427, "desc" : "Here are the slides in MDCC 2016 Android Session." },
{ "_id" : "joe-shenouda/awesome-cyber-skills", "countall" : 27, "desc" : "A curated list of hacking environments where you can train your cyber skills legally and safely" },
{ "_id" : "vhf/v8-bailout-reasons", "countall" : 119, "desc" : "A list of Crankshaft bailout reasons with examples" },
{ "_id" : "hemanth/functional-programming-jargon", "countall" : 1396, "desc" : "Jargon from the functional programming world in simple terms!" },
{ "_id" : "jtoy/awesome-tensorflow", "countall" : 707, "desc" : "TensorFlow - A curated list of dedicated resources http://tensorflow.org" },
{ "_id" : "mgp/book-notes", "countall" : 93, "desc" : "Notes from interesting things that I've read." },
{ "_id" : "ZQiang94/Andriod-collect-blogs", "countall" : 101, "desc" : ":rose:" },
{ "_id" : "tunz/js-vuln-db", "countall" : 233, "desc" : "A collection of JavaScript engine CVEs with PoCs" },
{ "_id" : "RPISEC/Malware", "countall" : 356, "desc" : "Course materials for Malware Analysis by RPISEC" },
{ "_id" : "brillout/awesome-react-components", "countall" : 1030, "desc" : "Catalog of React components / libraries" },
{ "_id" : "paramminhas/star", "countall" : 120, "desc" : "another github hack" },
{ "_id" : "karan/Projects", "countall" : 486, "desc" : ":page_with_curl: A list of practical projects that anyone can solve in any programming language." },
{ "_id" : "marktony/Awesome_API", "countall" : 173, "desc" : "A collection of APIs" },
{ "_id" : "xem/minix86", "countall" : 102, "desc" : "x86 (MS-DOS) documentation, disassembler and emulator - WIP" },
{ "_id" : "tuchk4/awesome-create-react-app", "countall" : 148, "desc" : "Awesome list of Create React App articles / tutorials / videos and FAQ" },
{ "_id" : "XXApple/AndroidLibs", "countall" : 224, "desc" : "正在成为史上最全分类 Android 开源代码大全~~~~（正在整理收集，不要着急~~先 Star 一下吧）" },
{ "_id" : "limetext/lime", "countall" : 269, "desc" : "Open source API-compatible alternative to the text editor Sublime Text" },
{ "_id" : "iron-io/dockers", "countall" : 239, "desc" : "Uber tiny Docker images for all the things. " },
{ "_id" : "egorsmkv/google-spaces", "countall" : 2779, "desc" : "Google Spaces about Computer Science" },
{ "_id" : "cargath/WWDC2016-Xcode-Color-Scheme", "countall" : 89, "desc" : "A color scheme for Xcode based on the WWDC 2016 invitation." },
{ "_id" : "RobinLinus/socialmedia-leak", "countall" : 145, "desc" : "A demo of cross origin login detection for most major web platforms" },
{ "_id" : "Abhishaker17/Awesome-APIs", "countall" : 81, "desc" : "A curated list of obscure and common APIs from round the web." },
{ "_id" : "seoul-opengov/opengov", "countall" : 266, "desc" : "서울시 행정정보 공개 깃허브입니다.(서울 정보소통광장) Github for the Seoul government information disclosure." },
{ "_id" : "ipfs/ipfs", "countall" : 233, "desc" : "IPFS - The Permanent Web" },
{ "_id" : "addyosmani/storage-on-the-web", "countall" : 88, "desc" : "🗃 Comparing storage options for the open web in 2016" },
{ "_id" : "toddmotto/public-apis", "countall" : 1655, "desc" : "A collective list of public JSON APIs for use in web development." },
{ "_id" : "qiu-deqing/FE-learning", "countall" : 41, "desc" : "结合个人经历总结的前端入门方法" },
{ "_id" : "jlantunez/webslides", "countall" : 1516, "desc" : "Making HTML presentations easy —" },
{ "_id" : "rougier/from-python-to-numpy", "countall" : 213, "desc" : "An open-access book on numpy vectorization techniques, Nicolas P. Rougier, 2017" },
{ "_id" : "adilyalcin/Keshif", "countall" : 115, "desc" : "Data Made Explorable" },
{ "_id" : "MiCode/patchrom_miui", "countall" : 71, "desc" : "The miui resources, apks, framework jars and the modified framework source code" },
{ "_id" : "git-sgmoore/OpenVPN_Ipsec_L2tp_server_on_Digital_Ocean", "countall" : 61, "desc" : "Steps I take when setting up a VPN server on Digital Ocean" },
{ "_id" : "quozd/awesome-dotnet", "countall" : 425, "desc" : "A collection of awesome .NET libraries, tools, frameworks and software" },
{ "_id" : "monostable/awesome-electronics", "countall" : 650, "desc" : "A curated list of awesome resources for electronic engineers and hobbyists" },
{ "_id" : "iRaul/awesome-portfolios", "countall" : 240, "desc" : "🎨 A curated list of Awesome Creative Portfolio Websites." },
{ "_id" : "elasticweb/nginx-configs", "countall" : 109, "desc" : "Nginx configurations for most popular CMS/CMF/Frameworks based on PHP" },
{ "_id" : "open-falcon/of-release", "countall" : 107, "desc" : "Open-Falcon Release" },
{ "_id" : "siggy/beatboxer", "countall" : 138, "desc" : "Drum machine in a few hundred lines of html/js/css" },
{ "_id" : "openfootball/football.json", "countall" : 34, "desc" : "Free open public domain football data in JSON incl. English Premier League, Bundesliga, Primera División, Serie A and more" },
{ "_id" : "openimages/dataset", "countall" : 384, "desc" : "The Open Images dataset" },
{ "_id" : "mathieudutour/git-sketch-plugin", "countall" : 52, "desc" : "A Git client generating pretty diffs built right into Sketch." },
{ "_id" : "elendirx/web2web", "countall" : 569, "desc" : "P2P web powered by torrents and blockchain." },
{ "_id" : "viatsko/awesome-vscode", "countall" : 108, "desc" : "A curated list of delightful VS Code packages and resources." },
{ "_id" : "acdlite/react-fiber-architecture", "countall" : 782, "desc" : "A description of React's new core algorithm, React Fiber" },
{ "_id" : "ElaWorkshop/awesome-cn-cafe", "countall" : 112, "desc" : "A curated list of awesome café places in China." },
{ "_id" : "tiimgreen/github-cheat-sheet", "countall" : 169, "desc" : "A list of cool features of Git and GitHub." },
{ "_id" : "PaddlePaddle/book", "countall" : 81, "desc" : null },
{ "_id" : "carpedm20/awesome-hacking", "countall" : 163, "desc" : "A curated list of awesome Hacking tutorials, tools and resources" },
{ "_id" : "wbkd/awesome-interactive-journalism", "countall" : 702, "desc" : "A list of awesome interactive journalism projects." },
{ "_id" : "abhishekbanthia/Awesome-APIs", "countall" : 2159, "desc" : "📚 A public list of APIs from round the web." },
{ "_id" : "Gorcenski/voting-machines", "countall" : 103, "desc" : "A repo for exploring the software quality of electronic voting machines" },
{ "_id" : "DroidKaigi/conference-app-2017", "countall" : 162, "desc" : "The Official Conference App for DroidKaigi 2017 Tokyo" },
{ "_id" : "ElemeFE/node-interview", "countall" : 267, "desc" : "How to pass the Node.js interview of ElemeFE." },
{ "_id" : "propwnadmin/EmptyProject", "countall" : 224, "desc" : "Public Key" },
{ "_id" : "stanzhai/be-a-professional-programmer", "countall" : 526, "desc" : "成为专业程序员路上用到的各种优秀资料、神器及框架" },
{ "_id" : "dcunited001/mri-scans", "countall" : 143, "desc" : "I open sourced my brain.  Here it is." },
{ "_id" : "Blankj/AndroidStandardDevelop", "countall" : 236, "desc" : "安卓开发规范(updating)" },
{ "_id" : "bmkmanoj/js-by-examples", "countall" : 136, "desc" : "Learn JavaScript by examples" },
{ "_id" : "shagunsodhani/papers-I-read", "countall" : 76, "desc" : "A-Paper-A-Week" },
{ "_id" : "terkelg/awesome-creative-coding", "countall" : 151, "desc" : "🎨 Creative Coding, Generative Art, Interaction Design, Resources." },
{ "_id" : "kdeldycke/awesome-falsehood", "countall" : 1304, "desc" : ":pill: Curated list of falsehoods programmers believe in." },
{ "_id" : "qyuhen/book", "countall" : 88, "desc" : "学习笔记" },
{ "_id" : "enaqx/awesome-pentest", "countall" : 138, "desc" : "A collection of awesome penetration testing resources, tools and other shiny things" },
{ "_id" : "kamranahmedse/developer-roadmap", "countall" : 2380, "desc" : "Roadmap to becoming a web developer in 2017" },
{ "_id" : "prasmussen/glot", "countall" : 148, "desc" : "Pastebin with runnable snippets and API" },
{ "_id" : "jlund/streisand", "countall" : 459, "desc" : "Streisand sets up a new server running L2TP/IPsec, OpenConnect, OpenSSH, OpenVPN, Shadowsocks, sslh, Stunnel, a Tor bridge, and WireGuard. It also generates custom instructions for all of these services. At the end of the run you are given an HTML file with instructions that can be shared with friends, family members, and fellow activists." },
{ "_id" : "forter/security-101-for-saas-startups", "countall" : 432, "desc" : "security tips for startups" },
{ "_id" : "puikinsh/gentelella", "countall" : 881, "desc" : "Free Bootstrap 3 Admin Template" },
{ "_id" : "joshbuchea/HEAD", "countall" : 4440, "desc" : "A list of everything that could go in the <head> of your document" },
{ "_id" : "nikitavoloboev/knowledge-map", "countall" : 34, "desc" : "🌍 knowledge index of things as mind maps (math, ai, programming and more) (alfred workflow included) (built with MindNode) (sharing my Anki decks) (contributions are most welcome) " },
{ "_id" : "neutraltone/awesome-stock-resources", "countall" : 132, "desc" : "A collection of links for free stock photography, video and Illustration websites." },
{ "_id" : "ro31337/bigoposter", "countall" : 242, "desc" : "Big-O Complexities / Poster of common algorithms used in Computer Science" },
{ "_id" : "open-android/Android", "countall" : 128, "desc" : "GitHub上最火的Android开源项目,所有开源项目都有详细资料和配套视频" },
{ "_id" : "grvcoelho/css", "countall" : 74, "desc" : "Opinionated CSS styleguide for scalable applications" },
{ "_id" : "praetorian-inc/Hob0Rules", "countall" : 86, "desc" : "Password cracking rules for Hashcat based on statistics and industry patterns" },
{ "_id" : "jwasham/coding-interview-university", "countall" : 324, "desc" : "A complete computer science study plan to become a software engineer." },
{ "_id" : "shagabutdinov/sublime-enhanced", "countall" : 461, "desc" : "Set of plugins for beloved sublime text editor" },
{ "_id" : "tallesl/Rich-Hickey-fanclub", "countall" : 165, "desc" : "\"every time I watch one of his talks I feel like someone has gone in and organized my brain\"" },
{ "_id" : "ValveSoftware/steam-audio", "countall" : 136, "desc" : "Steam Audio" },
{ "_id" : "LFeh/frontend-challenges", "countall" : 177, "desc" : ":boom: Listing some playful open-source's challenges of jobs to testing your knowledge" },
{ "_id" : "wireapp/wire", "countall" : 183, "desc" : "Overview of the open source code for Wire" },
{ "_id" : "notwaldorf/frankly", "countall" : 50, "desc" : ":wrench: A Polymer dashboard of issues/PRs for any number of GitHub repos" },
{ "_id" : "HarrisHan/LeagueofLegends", "countall" : 95, "desc" : "clear old project" },
{ "_id" : "LittleFriendsGroup/AndroidSdkSourceAnalysis", "countall" : 896, "desc" : "android sdk 源码解析——旨在帮助Android开发者更好的学习Android！我们只是一群普通的程序员，但是，我们热爱分享，想热热闹闹的玩点有意义的事！如果你也想陪我们一起愉快的玩耍，欢迎加入我们！Issues认领分析文章！" },
{ "_id" : "ValveSoftware/SteamVR-for-Linux", "countall" : 92, "desc" : "Issue tracker for the Linux port of SteamVR" },
{ "_id" : "pythias/NewParent", "countall" : 96, "desc" : "奶爸攻略" },
{ "_id" : "Notedown-cn/wxopen", "countall" : 293, "desc" : "微信公众平台 |小程序 API文档 http://wxopen.notedown.cn/" },
{ "_id" : "bloodycoder/Zhihu_craw", "countall" : 578, "desc" : "抓用户信息" },
{ "_id" : "mafintosh/awesome-p2p", "countall" : 87, "desc" : "List of great p2p resources" },
{ "_id" : "ironmaniiith/testIt", "countall" : 288, "desc" : "Test repo" },
{ "_id" : "NecronomiconCoding/NecroBot", "countall" : 87, "desc" : "The biggest Pokemon Go Bot in history. Good Bye!" },
{ "_id" : "jobbole/awesome-python-cn", "countall" : 214, "desc" : "Python资源大全中文版，内容包括：Web框架、网络爬虫、网络内容提取、模板引擎、数据库、数据可视化、图片处理、文本处理、自然语言处理、机器学习、日志、代码分析等" },
{ "_id" : "IonicaBizau/git-stats", "countall" : 60, "desc" : ":four_leaf_clover: Local git statistics including GitHub-like contributions calendars." },
{ "_id" : "cctanfujun/android-tips-tricks-cn", "countall" : 271, "desc" : "震惊！这么多的安卓开发Tips" },
{ "_id" : "devlint/gridlex", "countall" : 212, "desc" : "Just a CSS Flexbox Grid System" },
{ "_id" : "twitter/scala_school", "countall" : 80, "desc" : "Lessons in the Fundamentals of Scala" },
{ "_id" : "jrothrock/server_notes", "countall" : 136, "desc" : "Personal notes on building/configuring a server" },
{ "_id" : "karpathy/paper-notes", "countall" : 102, "desc" : "Random notes on papers, likely a short-term repo." },
{ "_id" : "w3c/svgwg", "countall" : 48, "desc" : "SVG Working Group specifications" },
{ "_id" : "mmccaff/PlacesToPostYourStartup", "countall" : 416, "desc" : "Compiled list of links from \"Ask HN: Where can I post my startup to get beta users?\"" },
{ "_id" : "mtomassoli/papers", "countall" : 65, "desc" : "Collection of papers" },
{ "_id" : "HumanOps/HumanOps", "countall" : 36, "desc" : "HumanOps deliberately highlights the importance of the teams running systems, not just the systems themselves." },
{ "_id" : "jwasham/google-interview-university", "countall" : 7819, "desc" : "A complete computer science study plan to become a software engineer." },
{ "_id" : "enddo/awesome-windows-exploitation", "countall" : 72, "desc" : "A curated list of awesome Windows Exploitation resources, and shiny things. Inspired by awesom" },
{ "_id" : "jlevy/og-equity-compensation", "countall" : 1683, "desc" : "Stock options, RSUs, taxes — a guide for humans" },
{ "_id" : "tpn/pdfs", "countall" : 112, "desc" : "PDF Collection" },
{ "_id" : "NotThePolice/CS-Go-Aimbot", "countall" : 298, "desc" : "CS-Go Aimbot for Win/Linux with all Bypasses" },
{ "_id" : "aviaryan/awesome-no-login-web-apps", "countall" : 31, "desc" : ":star2: Awesome (free) web apps that work without login" },
{ "_id" : "oxford-cs-deepnlp-2017/lectures", "countall" : 2505, "desc" : " Oxford Deep NLP 2017 course" },
{ "_id" : "arslanbilal/git-cheat-sheet", "countall" : 29, "desc" : ":octocat: git cheat sheet and git flow" },
{ "_id" : "Siddharth11/Colorful", "countall" : 45, "desc" : "A curated list of awesome resources to choose your next color scheme" },
{ "_id" : "GeniusVJR/LearningNotes", "countall" : 565, "desc" : "Enjoy Learning." },
{ "_id" : "dspinellis/unix-history-repo", "countall" : 156, "desc" : "Continuous Unix commit history from 1972 until today" },
{ "_id" : "ewwhite/zfs-ha", "countall" : 122, "desc" : "ZFS High-Availability NAS" },
{ "_id" : "nuprl/10PL", "countall" : 145, "desc" : "10 papers that all PhD students in programming languages ought to know, for some value of 10" },
{ "_id" : "claudepache/es-optional-chaining", "countall" : 118, "desc" : "ECMAScript proposal for Optional Chaining (aka Existential Operator, aka Null Propagation)" },
{ "_id" : "Douane/Douane", "countall" : 42, "desc" : "A modern GNU/Linux firewall for GNOME" },
{ "_id" : "larsbrinkhoff/awesome-cpus", "countall" : 183, "desc" : "All CPU and MCU documentation in one place" },
{ "_id" : "lizhangqu/CoreLink", "countall" : 233, "desc" : "Android 开发中的日常积累" },
{ "_id" : "noffle/art-of-readme", "countall" : 669, "desc" : ":love_letter: Learn the art of writing quality READMEs." },
{ "_id" : "ericjang/awesome-graphics", "countall" : 79, "desc" : "Curated list of computer graphics tutorials and resources" },
{ "_id" : "tawian/text-spinners", "countall" : 311, "desc" : "Pure text, CSS only, font independent, inline loading indicators" },
{ "_id" : "gowebexamples/gowebexamples", "countall" : 87, "desc" : "Go Web Examples Generator" },
{ "_id" : "Quartz/bad-data-guide", "countall" : 352, "desc" : "An exhaustive reference to problems seen in real-world data along with suggestions on how to resolve them." },
{ "_id" : "chemouna/HaskellResources", "countall" : 64, "desc" : "Compilation of useful resources for learning Haskell" },
{ "_id" : "ZuzooVn/machine-learning-for-software-engineers", "countall" : 3440, "desc" : "A complete daily plan for studying to become a machine learning engineer." },
{ "_id" : "mgattozzi/rust-from-lang", "countall" : 52, "desc" : "Rust::from(lang) - a repo to help learn Rust from a language you know!" },
{ "_id" : "dherman/defense-of-dot-js", "countall" : 86, "desc" : "In Defense of .js: A Proposal for Node.js Modules" },
{ "_id" : "silverbux/laravel-angular-admin", "countall" : 56, "desc" : "Laravel + Angularjs + Bootstrap + AdminLTE binded by Gulp workflow Admin Dashboard Boilerplate / Starter. " },
{ "_id" : "vhf/free-programming-books", "countall" : 3850, "desc" : ":books: Freely available programming books" },
{ "_id" : "metagrover/ES6-for-humans", "countall" : 1024, "desc" : "A kickstarter guide to writing ES6." },
{ "_id" : "McFrankline/Blockchain-stuff", "countall" : 221, "desc" : "Blockchain and Crytocurrency Resources" },
{ "_id" : "ThinkDevelopers/PHPConChina", "countall" : 78, "desc" : "" },
{ "_id" : "shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words", "countall" : 97, "desc" : "List of Dirty, Naughty, Obscene, and Otherwise Bad Words" },
{ "_id" : "bpesquet/thejsway", "countall" : 107, "desc" : "Manuscript of the book \"The JavaScript Way\"" },
{ "_id" : "ry/deep_learning_glossary", "countall" : 51, "desc" : "Simple, opinionated explanations of various things encountered in Deep Learning" },
{ "_id" : "symfony/skeleton", "countall" : 88, "desc" : "The Symfony Flex skeleton" },
{ "_id" : "facert/python-data-structure-cn", "countall" : 290, "desc" : "problem-solving-with-algorithms-and-data-structure-using-python 中文版" },
{ "_id" : "g13nn/Email-Framework", "countall" : 87, "desc" : "Responsive HTML Email Framework" },
{ "_id" : "pickhardt/maintainers-wanted", "countall" : 109, "desc" : "List of projects looking for new lead maintainers, either abandoned or just looking for someone else to lead." },
{ "_id" : "teesloane/Auth-Boss", "countall" : 148, "desc" : "Become an Auth Boss. Learn about different authentication methodologies on the web." }
]
